### ISSUE TITLE
Copy URL to clipboard on serialization

### ISSUE THREAD

**Issue by tylermcginnis** [tylermcginnis/javascriptvisualizer#16]

**Comment by labtocat** [comment]
@tylermcginnis can you give me more idea on this? is it to copy URL or copy contents?

**Comment by tylermcginnis** [comment]
Just copy the URL. Then probably have some sort of toast UI that tells the user.

**Comment by neosiae** [comment]
@labtocat Do you plan to work on this? I already have something.

**Comment by labtocat** [comment]
@neosiae If u already have something, go ahead (y)
