### ISSUE TITLE
Buttons are pushed off screen

### ISSUE THREAD

**Issue by makeupsomething** [tylermcginnis/javascriptvisualizer#23]
Adding more than 20 lines of code begins to push the buttons in the topbar off screen. No amount of scrolling can bring them back.

<img width="854" alt="tyler" src="https://user-images.githubusercontent.com/7676733/46708398-5ee56080-cc79-11e8-8b48-0e351ac5c5ab.png">

**Comment by labtocat** [comment]
Pull Request #25
