### ISSUE TITLE
Phase don't change from Creation to Execution

### ISSUE THREAD

**Issue by karataev** [tylermcginnis/javascriptvisualizer#34]
It seems that JS Visualizer has a bug with detecting a phase change. It's always in **creation** phase, but should change to **execution** when code runs.

![js-viz](https://user-images.githubusercontent.com/12277086/47267566-bc2dbb80-d56f-11e8-822b-d1aa1558d496.gif)

**Comment by tylermcginnis** [comment]
Gah good find.
